// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzaid_fqnvjn0bymhDaTU_VeytgT6Y6nw',
    appId: '1:1057096459013:web:eadf15d086b2217a388d6c',
    messagingSenderId: '1057096459013',
    projectId: 'login-app-fbd78',
    authDomain: 'login-app-fbd78.firebaseapp.com',
    storageBucket: 'login-app-fbd78.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa8WD5ol3JG6PC7egDAilhEHrRJIy-z2E',
    appId: '1:1057096459013:android:10c7a312a8f10f36388d6c',
    messagingSenderId: '1057096459013',
    projectId: 'login-app-fbd78',
    storageBucket: 'login-app-fbd78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfJRQQmMY-4w0srHDxB7XIFBrbNRvfqFM',
    appId: '1:1057096459013:ios:d2460836c564a66b388d6c',
    messagingSenderId: '1057096459013',
    projectId: 'login-app-fbd78',
    storageBucket: 'login-app-fbd78.appspot.com',
    iosBundleId: 'com.example.loginResponsive',
  );
}
